name: Build sys-tweak

on:
  workflow_dispatch:
  repository_dispatch:
    types: [push]
    repositories:
      p-sam/switch-sys-tweak

permissions:
  contents: write

jobs:
  container-build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
      - name: env
        run: |
          cat /proc/cpuinfo
          free -m

      - name: checkout - project
        uses: actions/checkout@v2
        with:
          repository: p-sam/switch-sys-tweak
          ref: develop
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global --add safe.directory /__w/sys-tweak-builds/sys-tweak-builds

      - name: Install deps - libnx
        run: |
          git clone https://github.com/switchbrew/libnx.git /tmp/libnx
          make -C /tmp/libnx install -j4

      - name: Install deps - ams libs
        run: |
          make -C lib/ams/libstratosphere -j4

      - name: Build sys-tweak with NACP override only
        run: |
          make clean
          make FEAT_NSRO_CONTROL="Y" FEAT_NSAM_CONTROL="Y" -j4

      - name: Get commit infos
        id: commit_info
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "sha=$COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Create Release and Upload files
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.CURRENT_DATE }}
          body: |
            Automatically generated from latest [p-sam/switch-sys-tweak](https://github.com/p-sam/switch-sys-tweak/) commit.
            [Commit details](https://github.com/p-sam/switch-sys-tweak/commit/${{ steps.commit_info.outputs.sha }})            
          release_name: Release ${{ env.CURRENT_DATE }}
          file_glob: true
          file: out/sys-tweak*.{zip,nsp}
